### ISSUE TITLE
Creating items through textual thing config results in crash

### ISSUE THREAD

**Issue by spacemanspiff2007** [spacemanspiff2007/HABApp#171]
This does not work
```yml
# Create items for every matching thing
create items:
  - type: Color
    name: '{thing_label, :(.+)$}_RGB_Manu'
    label: '{thing_label, :(.+)$} Farbe'

```
