### ISSUE TITLE
thing_*.yml and rules not reloaded by HABApp

### ISSUE THREAD

**Issue by Etzeitet** [spacemanspiff2007/HABApp#198]
This is in reference to a comment made in issue #197 about files not being reloaded by HABApp.

I first noticed that HABApp sometimes would not reload changes made to `thing_<whatever>.yml` files, usually requiring a restart of HABApp. I also noticed the same issue with Python scripts in the `rules` directory.

By chance I fixed the issue by deleting all the log files in `/var/log/openhab` and restarting HABApp. However, I noticed the next day the issue had returned. Taking a closer look I did see the following error in the `HABApp.log`:

```
[2021-01-17 12:13:32,026] [              HABApp.Rule]  WARNING | /usr/lib/python3.7/logging/handlers.py:1326: ResourceWarning:unclosed file <_io.TextIOWrapper name='/var/log/openhab/HABApp_events.log' mode='a' encoding='utf-8'>
```
Deleting the `HABApp_events.log` files and restarting fixed the issue. I don't know why the issue with reloading came back - I hadn't done anything with HABApp between fixing it originally and the issue returning.

I don't have much of the original logs (due to deleting them), but if there are any specific things you want me to try/do, let me know and I can provide any relevant logs.

## System Info:
HABApp v 0.19.1
OpenHABian
OpenHAB 3
Raspberry Pi 3B+

**Comment by spacemanspiff2007** [comment]
I have pushed a new version to the dev branch that contains a logger for the raw file events.
Can you please test if the events are still coming from the file system and HABApp just ignores them?
(Just download the developement branch and replace the sources in ``/opt/habapp/lib/python3.X/site-packages/HABApp`` or wherever you installed it to.)

Can you add the logger with DEBUG to your logging configuration.
```
loggers:
  ...
  HABApp.file_events:
    level: DEBUG
```

You'll then have the events in your HABApp.log

**Comment by Etzeitet** [comment]
I have installed the Development code and so far the file_events logger is working. I will keep an eye on things and see if the issue occurs again. 

I setup the logger as follows:

handler:

```
  FileEventFile:
    class: HABApp.core.lib.handler.MidnightRotatingFileHandler
    filename: HABApp_file_events.log
    maxBytes: 1_048_576
    backupCount: 3
    formatter: HABApp_format
    level: DEBUG
```

logger:

```
  HABApp.file_events:
    level: DEBUG
    handlers:
      - FileEventFile
    propagate: False
```

Let me know if there is anything that should be done differently.
