### ISSUE TITLE
Default Handler for Loggers

### ISSUE THREAD

**Issue by loewexy** [spacemanspiff2007/HABApp#200]
It would be nice to have default settings for loggers not mentioned in `logging.yml`. Since for all my rules I mostly want to have the same settings this would require much less configuration.

If this is already possible it would be nice to add this to the documentation.

**Comment by Etzeitet** [comment]
You can create a logger based off an existing handler:

In your rules script:

```
log = logging.getLogger("HABApp.my_rule")
log.info("Hello, this is my_rule!)
```

HABApp.log:

```
[2021-01-18 22:47:57,185] [             HABApp.Rules]    DEBUG | Loading file: /etc/openhab/habapp/rules/myrule.py
[2021-01-18 22:47:57,193] [           HABApp.my_rule]     INFO | Hello, this is my_rule!
[2021-01-18 22:47:57,196] [           HABApp.my_rule]     INFO | Initialise
```

The downside here is having your own logs written to a possibly already busy HABApp log file.

Another option is to define a single new logger and use it as above:

logging.yaml

```
handlers:
  # adjust names/paths as required
  TestRuleHandler:
    class:  HABApp.core.lib.handler.MidnightRotatingFileHandler
    filename: /var/log/openhab/my_habapp_rules.log
    maxBytes: 10_000_000
    backupCount: 3
    formatter: HABApp_format
    level: DEBUG

loggers:
  TestRule:
    level: DEBUG
    handlers:
      - TestRuleHandler
    propagate: False
```

You can then use `log = logging.getLogger("TestRule.my_rule")` as before, adjusting `my_rule` to be whatever you want in each of your rules files. This will still put all the different rules' logs into the same file, but at least it is separate.

You could, of course, completely configure the logging module in your rules files, including handlers and where logs are written to. Though at this point it's probably just as much effort as updating the yaml to add new handlers.
