### ISSUE TITLE
[Help] Configure logging to output to stdout

### ISSUE THREAD

**Issue by dafzor** [spacemanspiff2007/HABApp#255]
Trying to configure all HABapp logging to use stdout.

It would seem it would need something like this:
```
  EventStream:
    class: logging.handlers.StreamHandler
    stream: sys.stdout

    formatter: HABApp_format
    level: DEBUG
```

However the above is not correct, could you point me to some documentation on how to properly configure this?

**Comment by spacemanspiff2007** [comment]
Could you try ```stream  : ext://sys.stdout``` (found [here](https://docs.python.org/3/library/logging.config.html#dictionary-schema-details)).

**Comment by dafzor** [comment]
Thanks, had class and stream incorrect. it works now.

**Comment by spacemanspiff2007** [comment]
Could you post the working config please?

**Comment by dafzor** [comment]
```
formatters:
  HABApp_format:
    format: '[%(asctime)s] [%(name)25s] %(levelname)8s | %(message)s'


handlers:
  # There are several Handlers available:
  # logging.handlers.RotatingFileHandler:
  #   Will rotate when the file reaches a certain size (see python logging documentation for args)
  # HABApp.core.lib.handler.MidnightRotatingFileHandler:
  #   Will wait until the file reaches a certain size and then rotate on midnight
  # More handlers:
  # https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler

  HABApp_default:
    class: HABApp.core.lib.handler.MidnightRotatingFileHandler
    filename: 'HABApp.log'
    maxBytes: 1_048_576
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  HABApp_console:
    class: logging.StreamHandler
    stream: ext://sys.stdout

    formatter: HABApp_format
    level: DEBUG

  EventFile:
    class: HABApp.core.lib.handler.MidnightRotatingFileHandler
    filename: 'events.log'
    maxBytes: 1_048_576
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  BufferEventFile:
    class: logging.handlers.MemoryHandler
    capacity: 10
    formatter: HABApp_format
    target: EventFile
    level: DEBUG

  EventStream:
    class: logging.StreamHandler
    stream: ext://sys.stdout

    formatter: HABApp_format
    level: DEBUG


loggers:
  HABApp:
    level: DEBUG
    handlers:
      - HABApp_default
      - HABApp_console
    propagate: False

  HABApp.EventBus:
    level: DEBUG
    handlers:
      - BufferEventFile
      - EventStream
    propagate: False
```
