### ISSUE TITLE
habapp stops working after openhab restart

### ISSUE THREAD

**Issue by niwla23** [spacemanspiff2007/HABApp#277]
Everytime I restart openhab habapp stops working until restarted. Running both on raspberry pi, openhab bare metal and habapp in docker

**Comment by spacemanspiff2007** [comment]
Do you get an error message in the log? What version are you running (python/HABapp).

**Comment by niwla23** [comment]
I am using this version: https://hub.docker.com/layers/habapp/spacemanspiff2007/habapp/v0.31.2/images/sha256-80ea4da4fa74daae8db1b2a2e25014daa772ff0f9c8f721e85e882dd0b6bbec4?context=explore

The issue does not appear all the time, sometimes it works, sometimes it doesn't. No errors in the logs.

**Comment by spacemanspiff2007** [comment]
The reconnect to openhab can take up to 3 minutes. Have you waited this long?

**Comment by niwla23** [comment]
yes. Another thing I have observed is that sometimes it just stops updating item state. I should mention that I have a long-running rule (~1 minute) to drive the garden gate.

**Comment by spacemanspiff2007** [comment]
Can you reproduce the issue with 1.0?

**Comment by niwla23** [comment]
I upgraded a few days ago, will tell you if it happens again.

**Comment by niwla23** [comment]
I have the problem again, it detects the disconnect then tries to reconnect while openHAB is still restarting (which takes 2 minutes to start up, not sure if that is normal). When it gets a real connection it seems to have not loaded the items and no rules are loaded. Heres the log file:

[HABApp.log](https://github.com/spacemanspiff2007/HABApp/files/9365105/HABApp.log)

**Comment by niwla23** [comment]
I have built a watchdog for restarting it automatically once a ping rule does not update anymore:

https://github.com/niwla23/habapp-watchdog

**Comment by spacemanspiff2007** [comment]
Could you try again with the config `wait_for_openhab` set to true?

Also I don't see a disconnect in any of the log files, just a failing connect during the startup of HABApp.
Could you try without your watchdog please so there is the log where it tries to reconnect?

**Comment by niwla23** [comment]
this is the config:
```yaml
directories:
  logging: log  # Folder where the logs will be written to
  rules: rules # Folder from which the rule files will be loaded
  param: params # Folder from which the parameter files will be loaded
  config: config # Folder from which configuration files (e.g. for textual thing configuration) will be loaded
  lib: lib # Folder where additional libraries can be placed
location:
  latitude: 0.0
  longitude: 0.0
  elevation: 0.0

openhab:
  connection:
    url: "https://openhab.b49.cloudserver.click"
    user: habapp
    password: tghwe4rgh48w7ghjw49jgwer9jg
  general:
    listen_only: false  # If True HABApp will not change anything on the openHAB instance.
    wait_for_openhab: true # If True HABApp will wait for items from the openHAB instance before loading any rules on startup
  ping:
    enabled: true  # If enabled the configured item will show how long it takes to send an update from HABApp and get the updated value back from openhabin milliseconds
    item: HABApp_Ping # Name of the Numberitem
    interval: 10 # Seconds between two pings
```

The logs I have posted are from before I wrote the watchdog

**Comment by niwla23** [comment]
This is my current config, wait_for_openhab is already set.

```yaml
directories:
  logging: log  # Folder where the logs will be written to
  rules: rules # Folder from which the rule files will be loaded
  param: params # Folder from which the parameter files will be loaded
  config: config # Folder from which configuration files (e.g. for textual thing configuration) will be loaded
  lib: lib # Folder where additional libraries can be placed
location:
  latitude: 0.0
  longitude: 0.0
  elevation: 0.0

openhab:
  connection:
    url: "https://openhab.b49.cloudserver.click"
    user: habapp
    password: password
  general:
    listen_only: false  # If True HABApp will not change anything on the openHAB instance.
    wait_for_openhab: true # If True HABApp will wait for items from the openHAB instance before loading any rules on startup
  ping:
    enabled: true  # If enabled the configured item will show how long it takes to send an update from HABApp and get the updated value back from openhabin milliseconds
    item: HABApp_Ping # Name of the Numberitem
    interval: 10 # Seconds between two pings
``` 

The logs are from before I wrote the watchdog
