### ISSUE TITLE
Configuration via Environment Variables

### ISSUE THREAD

**Issue by JHK** [spacemanspiff2007/HABApp#399]
It would be great when the configuration could support injection from environment variables. With [envyaml](https://pypi.org/project/envyaml/) there also seems to be a library, that supports it already in a way similar to others (e.g. [Elastic](https://www.elastic.co/guide/en/beats/winlogbeat/current/using-environ-vars.html)) are supporting this already.

A configuration snippet with environment variables could then look like:
```yaml
openhab:
  connection:
    url: ${OPENHAB_URL}
    user: ${OPENHAB_USER}
    password: ${OPENHAB_PASSWORD}
```

My use case is, that I'd like to add the `config.yml` to the VCS, whilst I consider adding credentials in plain text to the VCS a bad practice.
