### ISSUE TITLE
inconsistent handling of "param" folder for "depends on"/"reloads on"

### ISSUE THREAD

**Issue by Rosi2143** [spacemanspiff2007/HABApp#474]
HABApp: 24.08.01
config,yml:
```yaml
directories:
  logging: /etc/openhab/habapp/logging # Folder where the logs will be written to
  #  logging: /etc/openhab/habapp/log # Folder where the logs will be written to
  rules: /etc/openhab/habapp/rules # Folder from which the rule files will be loaded
  param: /etc/openhab/habapp/param # Folder from which the parameter files will be loaded
  config: /etc/openhab/habapp/config # Folder from which configuration files (e.g. for textual thing configuration) will be loaded
  lib: lib # Folder where additional libraries can be placed
  ...
```

extract from logFile for the RequestFileLoadEvent
```
[2025-01-04 16:10:26,711] [               Exceptions]     INFO | File loaded: <RequestFileLoadEvent filename: rules/groupCheck.py>
[2025-01-04 16:11:09,128] [               Exceptions]     INFO | File loaded: <RequestFileLoadEvent filename: params/groups.yml>
```

When I want to add a dependency to any file in the "parameter Folder" aka `param`

I need to add this to the top of my file:
```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# HABApp:
#   depends on:
#    - params/groups.yml
#   reloads on:
#    - params/groups.yml
...
```

Why is the required "name" of the folder "params" even though in reality it is "param"?
