### ISSUE TITLE
Logging does not rotate logs

### ISSUE THREAD

**Issue by NickWaterton** [spacemanspiff2007/HABApp#76]
I think I have a problem with my `logging.yml` file.

My rules log file stops logging when it reaches 100000000 instead or rotating to a new log file.

This is the log file:
```
-rw-r--r-- 1 openhab openhab  3428555 Oct  1 08:10 HABAppevents.log
-rw-r--r-- 1 openhab openhab 10485632 Oct  1 08:01 HABAppevents.log.1
-rw-r--r-- 1 openhab openhab 10485757 Oct  1 07:32 HABAppevents.log.2
-rw-r--r-- 1 openhab openhab 10485683 Oct  1 07:03 HABAppevents.log.3
-rw-r--r-- 1 openhab openhab     1393 Oct  1 01:56 HABApp.log
-rw-r--r-- 1 openhab openhab  9999986 Sep 30 17:49 HABApprules.log
```
As you can see `HABAppevents.log` rotates as expected, but `HABApprules.log` does not.
This is my logging.yml file:
```
version : 1

formatters:
  HABApp_format:
          format: '[%(asctime)s] [%(name)26s] %(levelname)8s | %(funcName)19s: %(message)s'

handlers:
  HABApp_default:
    class: logging.handlers.RotatingFileHandler
    filename: 'HABApp.log'
    maxBytes: 10_485_760
    backupCount: '3'

    formatter: HABApp_format
    level: DEBUG

  EventFile:
    class: logging.handlers.RotatingFileHandler
    filename: 'HABAppevents.log'
    maxBytes: 10_485_760
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  BufferEventFile:
    class: logging.handlers.MemoryHandler
    capacity: 10
    formatter: HABApp_format
    target: EventFile
    level: DEBUG

  MyRuleHandler:
    class: logging.handlers.RotatingFileHandler
    filename: 'HABApprules.log'    # absolute filename is recommended
    maxBytes: 10_000_000
    backupCount: '3'

    formatter: HABApp_format  # use the specified formatter (see above)
    level: DEBUG

  BufferRuletFile:
    class: logging.handlers.MemoryHandler
    capacity: 10
    formatter: HABApp_format
    target: MyRuleHandler
    level: DEBUG


loggers:
  HABApp:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.EventBus:
    level: INFO
    handlers:
      - BufferEventFile
    propagate: False

  MyRule:
    level: DEBUG
    handlers:
      - BufferRuletFile
    propagate: False
```

Can you tell me what I've got wrong? I've tried without the BufferRuletFile as well, and that does the same thing.

Thanks.
